# Generated by Django 6.0.5 on 2026-06-04 19:15

import django.db.models.deletion
from django.db import migrations, models

# --- FUNGSI TAMBAHAN ---
def create_initial_data(apps, schema_editor):
    Category = apps.get_model('app_1', 'Category')
    Status = apps.get_model('app_1', 'Status')
    
    Category.objects.create(id=1, name="No Category")
    Category.objects.create(name="Manga")
    Category.objects.create(name="Manhua")
    Category.objects.create(name="Manhwa")
    
    Status.objects.create(id=1, name="No Status")
    Status.objects.create(name="On Going")
    Status.objects.create(name="Completed")
# -----------------------

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReadingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('chapters', models.IntegerField(default=0)),
                ('season', models.CharField(blank=True, default='-', max_length=10, null=True)),
                ('rating', models.CharField(default='-', max_length=10)),
                ('synopsis', models.TextField(blank=True, default='-', null=True)),
                ('notes', models.CharField(blank=True, default='-', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reading_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='items', to='app_1.category')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='items', to='app_1.status')),
            ],
        ),
        # --- TAMBAHKAN INI ---
        migrations.RunPython(create_initial_data),
        # ---------------------
    ]