# Generated by Django 6.0.5 on 2026-07-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['name'], 'verbose_name_plural': 'Type'},
        ),
    ]
