# Generated by Django 6.0.5 on 2026-07-10 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_alter_type_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('chapters', models.IntegerField(default=0)),
                ('season', models.CharField(blank=True, default='-', max_length=10, null=True)),
                ('synopsis', models.TextField(blank=True, default='-', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app_1.type')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app_1.status')),
                ('tags', models.ManyToManyField(blank=True, to='app_1.tag')),
            ],
        ),
        migrations.AddField(
            model_name='readingitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='app_1.tag'),
        ),
    ]
