# Generated by Django 6.0.5 on 2026-07-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_profile_cover_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='music_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
