# Generated by Django 6.0.5 on 2026-06-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_auto_20260607_1952'),
        ('app_1', '0004_importhistory'),
    ]

    operations = [
    ]
