# Generated by Django 6.0.5 on 2026-06-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_merge_0002_auto_20260607_1952_0004_importhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='importhistory',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='import_backups/'),
        ),
    ]
