# Generated by Django 6.0.5 on 2026-07-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0005_profile_music_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='music_link',
            new_name='music_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='music_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='thumbnail_music_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
