# Generated by Django 6.0.5 on 2026-07-11 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0006_rename_music_link_profile_music_url_profile_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='music_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='music_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='thumbnail_music_url',
        ),
    ]
