# Generated by Django 6.1 on 2026-08-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0007_remove_profile_artist_remove_profile_music_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reminder_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reminder_frequency',
            field=models.IntegerField(default=30),
        ),
    ]
